---

- hosts: all
  become: true
  pre_tasks:

  - name: update repo cache (OracleLinux)
    tags: always
    yum:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "OracleLinux"

- hosts: all
  become: true
  tasks:

  - name: add ssh key for kufor
    tags: always
    authorized_key:
      user: kufor
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFJWcXLsW5yVSYKpOUiskbehQcvY5f0uGrV/667UKm7L marek.topolcansky@telekom.com"

- hosts: workstations
  become: true
  tasks:

  - name: install terraform
    unarchive:
      src: /tmp/mtopolca/terraform_0.12.28_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 package
    tags: apache,apache2,sles
    zypper:
      name: apache2
      state: latest
    when: ansible_distribution == "SLES"

  - name: add Development files for the Apache Portable Runtime (APR) Utility Library
    zypper:
      name: apr-util-devel
      state: latest
    when: ansible_distribution == "SLES"

  - name: start apache (SLES)
    tags: apache,apache2,sles
    service:
      name: apache2
      state: started
      enabled: yes
    when: ansible_distribution == "SLES"

  - name: change e-mail address for admin
    tags: apache,apache2,sles
    lineinfile:
      path: /etc/apache2/vhosts.d/vhost.template
      regexp: '^ServerAdmin'
      line: ServerAdmin somebody@somewhere.net
    when: ansible_distribution == "SLES"
    register: apache2

  - name: restart apache2 (SLES)
    tags: apache,apache2,sles
    service:
      name: apache2
      state: restarted
    when: apache2.changed

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /srv/www/htdocs/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb pakage (OracleLinux)
    tags: oraclelinux,db,mariadb
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "OracleLinux"
