- name: install apache2 package
  tags: apache,apache2,sles
  package:
    name:
      - "{{ apache_package_name }}"
      - "{{ apr_util_package_name }}"
    state: latest

- name: start and enable apache service (SLES)
  tags: apache,apache2,sles
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: change e-mail address for admin
  tags: apache,apache2,sles
  lineinfile:
    path: /etc/apache2/vhosts.d/vhost.template
    regexp: '^ServerAdmin'
    line: ServerAdmin somebody@somewhere.com
  when: ansible_distribution == "SLES"
  notify: restart_apache

- name: copy default html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /srv/www/htdocs/index.html
    owner: root
    group: root
    mode: 0644
