- name: add ssh key for kufor
  authorized_key:
    user: kufor
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFJWcXLsW5yVSYKpOUiskbehQcvY5f0uGrV/667UKm7L marek.topolcansky@telekom.com"

- name: generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd
